### ISSUE TITLE
個別地圖機率運算

### ISSUE THREAD

**Issue by JAG3R** [lprensoft/FlowerMaster#1]
如果可以抽取Flash的資料
那如果在開始前先讀取地圖資料
用模擬的方式一個一個組合去嘗試
找出過關機率最高的組合方式
不知道這可不可行?

我有寫過類似的模擬
(可以參考這個=w=：https://github.com/JAG3R/flower-knight-probability-calculator
但會有些限制...
像是沒法估計是否會滅團

**Comment by lprensoft** [comment]
这个方式估计不太行，主要就是你提到的灭团问题。
毕竟队伍里面的花骑本来技能什么的都是随机的，很难解决这一大堆随机的问题。
