### ISSUE TITLE
在部分链接无法访问的情况下会出现flash定位错误

### ISSUE THREAD

**Issue by ggg17226** [lprensoft/FlowerMaster#2]
RT，我用的自己写的pac，没有把全部连接都走代理，游戏窗口定位偏移，并且游戏过程中可能会突发性的页面向上滚动，部分游戏画面被遮挡

**Comment by JAG3R** [comment]
我也有發生定位錯誤的問題，是不是flash抽取樣式的部分要修改一下??

**Comment by lprensoft** [comment]
@ggg17226 @JAG3R 这个问题一般是FLASH抽取代码载入问题导致的，解决办法：选择”设置“界面，然后点击”FLASH抽取代码”下面的“还原默认“按钮，然后点击”保存“按钮保存设置。回到”主页“界面，点击右下角的”重新载入“按钮，稍候片刻即可。

**Comment by JAG3R** [comment]
成功了!感謝 >W<
