### ISSUE TITLE
對應dmm上的繁中服

### ISSUE THREAD

**Issue by onlykevinpan** [lprensoft/FlowerMaster#21]
游戏首页
Cht : http://games.dmm.com/zh-CHT/detail/flower_Gro/
ChtR18 : http://games.dmm.co.jp/zh-CHT/detail/flower-x_Gro/
游戏页列
Cht : http://pc-play.games.dmm.co.jp/play/flower_Gro/
ChtR18 : http://pc-play.games.dmm.co.jp/play/flower-x_Gro/
新闻页面
https://cf.fkg.dmmgames.com/help/index.html

目前初步看來，封包對應似乎是跟日服一樣，暫時沒有發現什麼BUG

**Comment by lprensoft** [comment]
嗯，已经推出支持的版本，欢迎下载使用。
