### ISSUE TITLE
上次更新之後 上面那條推薦其他遊戲的會蓋住畫面

### ISSUE THREAD

**Issue by LizardCE** [lprensoft/FlowerMaster#25]
如題
後來我在flash抽取加了
.dmm-ntgnavi{
    display:none;
}
就好了
我不確定這是個案還是大家都會這樣，
本人css沒學得多好，可能還有更好的解決方案，不過還是先丟上來說一下

**Comment by lprensoft** [comment]
嗯，解决的办法有很多，后面我会整合一个比较好的方案进去。
