### ISSUE TITLE
有關1.5.1 更新後的Flash抽取代碼

### ISSUE THREAD

**Issue by LinFamBee** [lprensoft/FlowerMaster#26]
你好!   事情是這樣子的，
原本1.5.0的預設代碼:
body {
    margin:0;
    overflow:hidden;
}
再加上:
.menu-list
{
display:none!important;
}
  這樣子會無邊界、無上面那條白白的遊戲布幕
但是我發現現在1.5.1的預設Flash抽取代碼，
會有遊戲布幕，以及無法無邊界。

我想要請問 現在這個Flash抽取代碼，
是多了哪一些功能呢?
 ※補充:推兔2.0 功能還是有些問題，例如:無法點進去花園的關卡選擇，一般的關卡選擇....等
 ※1.5.1 以測試 可使用 上面的代碼，無問題!

**Comment by lprensoft** [comment]
由于抽取代码忘记更新了，因此1.5.1的抽取代码实际上跟1.5.0是相同的。
这个问题会在后继推出一个小版本解决。
推兔2.0的功能，是由另一个开发者维护的，建议你与他联系，把详细的情况告知他。
PS: 建议推兔2.0使用推上一次图功能，可以解决各种奇怪的问题。

**Comment by LinFamBee** [comment]
@lprensoft 你好 請問是#5thYL 這一位嗎?

**Comment by lprensoft** [comment]
@LinFamBee 是的，就是了。
