### ISSUE TITLE
錯誤測試&建議 2017/3/4

### ISSUE THREAD

**Issue by kingdom84521** [lprensoft/FlowerMaster#3]
1. 當遊戲主動重整頁面時，Flash視窗無法再鎖定
2. 最近新出的水影秘石的碎片日誌未記載
3. 建議轉蛋日誌多做整理，維持版面整齊(EX: 照星等排列，並縮排整理)
4. 視窗縮小時靜音設定有誤，變成"縮小時靜音/開啟聲音"

另外，希望能加入隊伍管理系統

**Comment by lprensoft** [comment]
@kingdom84521 1.再锁定需要等待页面完全载入后，如果确实没有再锁定，可以手动点击右下角的”重新载入“按钮进行手动锁定。2.这个会看活动情况而决定是否要追加。3.请更具体的说明下建议是怎样的。4.这个情况是由于点击静音是在游戏FLASH载入之前，导致音效管理没生效引起的，建议在进入游戏后再进行操作。
另外，队伍管理系统具体想要怎样的功能，也请进一步说明，谢谢你的建议。
