### ISSUE TITLE
日服大改版 版型變16比9 這有人救嗎

### ISSUE THREAD

**Issue by Saneypig** [lprensoft/FlowerMaster#33]
2019/6/17 日服改了網頁版的版型了 求救大老~~

**Comment by dghkd** [comment]
我抽換了瀏覽器核心
改用Chromium的核心做了一版
由於大改有不少功能受影響
一時之間修不了那麼多，也沒空一項項去測
基本的自動推圖點擊功能修好了
可以先湊合著用
https://github.com/dghkd/FlowerMaster/releases/tag/v1.4.9

另外我那邊是繼承lprensoft大老的1.4.7版本
再自行開發新功能的分支版本
所以不會有這邊的推圖2.0功能
以後也不會有

**Comment by Saneypig** [comment]
我改用~~1.4.9 後發現我的電腦會跑版型 Flash 抽取後放大 
![image](https://user-images.githubusercontent.com/19524098/59852241-00908600-93a1-11e9-9650-a63024528d4c.png)
![image](https://user-images.githubusercontent.com/19524098/59852308-2158db80-93a1-11e9-8f56-615ad40c5c97.png)

企圖修復這邊的檔案 但不知為啥Flash 抽取後 卻點擊不到畫面
淚流滿面 兩邊都卡關

**Comment by dghkd** [comment]
看起來比例怪怪的
你電腦的顯示設定放大倍率是不是超過100%?

現在花騎已經全面移植為HTML5
Flash已經廢除了
這邊的程式碼仍然是舊的IE核心
對HTML5的支援可能不是那麼好
所以點擊遊戲畫面沒有反應
也正因為這樣我才會去抽換瀏覽器核心

**Comment by Saneypig** [comment]
後來重設調整是有恢復了~~  能使用了感謝

**Comment by lprensoft** [comment]
我最近也在看这个要怎么改，可能需要点时间，谢谢你提供的临时版本和解决方案。

**Comment by Saneypig** [comment]
感謝大老們還積極修改，實力太差~~修不動一直撞牆XF
