### ISSUE TITLE
關於提醒設置及建議功能

### ISSUE THREAD

**Issue by JAG3R** [lprensoft/FlowerMaster#7]
*請問提醒設置是一定要在背景運作下才會有的功能嗎?

*能不能新增功能-當體力回復到某一數值就自動打某個關卡，探索點數滿一格也自動開啟探索來回復點數。
 然後希望可以設定執行以上程序的:
        1. 開始時間
        2. 結束時間
        3. 體力的數值
        4. 目標關卡

這樣刷活動或刷強化靈會比較有效率~
感謝><

**Comment by lprensoft** [comment]
提醒是需要运作才能看得到的，不管当前窗口是隐藏还是显示的。
下面这些自动功能并不考虑开发，一开始程序初衷就是出于简化推图顺带加上日志功能和提醒功能等而设计。并没有打算做成一个全自动的机器人程序，这样也是违反官方协议的。所以这些让她进一步变成自动化机器人的功能是不考虑开发的。

**Comment by JAG3R** [comment]
我想我應該能夠自己修改一下，我看你有加很多註解我應該可以讀懂
可以教我怎把這些檔案集結成exe檔嗎?
我有查了一下但還是不知道怎用(我剛接觸這些東西= =|||

**Comment by lprensoft** [comment]
你需要安装一套Visual Studio程式就可以了，最好使用最新的Visual Studio 2017
