### ISSUE TITLE
游戏窗口顶部总是弹出IE的提示

### ISSUE THREAD

**Issue by lan23333** [lprensoft/FlowerMaster#8]
![s_1 9hu t7arj6a2kgpczsj](https://user-images.githubusercontent.com/375928/31572363-5076d354-b072-11e7-9648-854d1c2f6fbc.png)

上面那个黄条，就算在IE设置了默认允许Active Content，这个也永远会弹出来

**Comment by lprensoft** [comment]
IE版本是？是不是最新的呢？

**Comment by lan23333** [comment]
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299
应该是最新的

**Comment by lprensoft** [comment]
额，这是Edge的版本吧，应该是IE的版本号。不过你是WIN10系统的话应该不会有什么问题，是Win10 1709么？

**Comment by lan23333** [comment]
Win 10 Pro Version 1709 OS Build 16299.64
IE: 11.64.16299.0
我曾经试过系统里禁用IE，然并卵
