### ISSUE TITLE
上次維修後就無法使用

### ISSUE THREAD

**Issue by LizardCE** [lprensoft/FlowerMaster#9]
如題 順帶一問 你讀Json用的套件是哪個版本的? 用nuget抓下來還是一堆紅字
-------------------------------
沒事 我後來把source code重新複製一分就好了

剩下的問題是，自從上次維修之後，就沒辦法用團長助理登入，一般瀏覽器都正常

**Comment by dghkd** [comment]
應該是Nekoxy的問題
更新Nekoxy之後就可以順利進入遊戲了
我fork後改了一份，你可以試試看
https://github.com/dghkd/FlowerMaster/releases/tag/v1.4.7

**Comment by LizardCE** [comment]
感謝 可以正常登入了
